swagger: "2.0"
info:
  version: "0.0.1"
  title: Netflix Api
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: users
    post:
      description: Creates new user
      operationId: createUser
      parameters:
        - name: user
          in: body
          required: true
          description: User data to create new user with
          schema:
            $ref: "#/definitions/CreateUserObject"
      responses:
        "201":
          description: Successfully created user
          schema:
            $ref: "#/definitions/UserObject"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/login:
    x-swagger-router-controller: users
    post:
      description: Logs in user
      operationId: login
      parameters:
        - name: credentials
          in: body
          required: true
          schema:
            $ref: "#/definitions/CreateUserObject"
      responses:
        "200":
          description: Successfully logged in user
          schema:
            type: object
            required:
              - sessionID
            properties:
              sessionID:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /videos:
    x-swagger-router-controller: videos
    get:
      description: Find video by video title
      operationId: findVideoByTitle
      parameters:
        - name: title
          in: query
          type: string
          required: true
        - name: sessionID
          in: header
          type: string
          required: true
      responses:
        "200":
          description: Found video
          schema:
            $ref: "#/definitions/VideoObject"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"      
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  CreateUserObject:
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
  UserObject:
    properties:
      id:
        type: string
      email:
        type: string
      password:
        type: string
  VideoObject:
    properties:
      id:
        type: string
      title:
        type: string
      year:
        type: number
