swagger: "2.0"
info:
  version: "0.0.1"
  title: Netflix Api
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: users
    post:
      description: Creates new user
      operationId: createUser
      parameters:
        - name: user
          in: body
          required: true
          description: User data
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Successfully created user
          schema:
            type: object
            properties:
              id:
                type: number
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/login:
    x-swagger-router-controller: users
    post:
      description: Logs in user
      operationId: login
      parameters:
        - name: credentials
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Successfully logged in user
          schema:
            type: object
            required:
              - X-Session-ID
            properties:
              X-Session-ID:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /videos:
    x-swagger-router-controller: videos
    get:
      description: Find video by video title
      operationId: findVideoByTitle
      parameters:
        - name: title
          in: query
          type: string
          required: true
        - name: X-Session-ID
          in: header
          type: string
          required: true
      responses:
        "200":
          description: Found video
          schema:
            type: object
            properties:
              id:
                type: number
              title:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"      
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
